# This is a sample build configuration for Docker.
# Check our guides at https://confluence.atlassian.com/x/O1toN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: atlassian/default-image:2

pipelines:
  default:
    - step: &sonarqube
          name: analyze with hawkman sonarqube server
          script:
             - mvn clean install
             - mvn org.jacoco:jacoco-maven-plugin:prepare-agent install
             - mvn org.pitest:pitest-maven:mutationCoverage
             - mvn sonar:sonar -Dsonar.test=src/test -Dsonar.projectKey=n-t-m-s -Dsonar.host.url=http://165.22.120.243:9000 -Dsonar.login=6fe927cb875c24260c41660607b8209bc40e1c94

  branches:
    master:
      - step: &build-deploy-docker-stable-version
          name: build and deploy to docker-hub
          services:
            - docker
          script:
            - export IMAGE=hawkmanlabs/nsoroma-tracker-monitoring-service
            - export IMAGE_NAME=hawkmanlabs/nsoroma-tracker-monitoring-service:$BITBUCKET_COMMIT
            - export IMAGE_NAME2=hawkmanlabs/nsoroma-tracker-monitoring-service:stable

            - docker build -t $IMAGE_NAME -t $IMAGE_NAME2 .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE
    
    develop:
      - step: &build-deploy-docker-development
          name: build and deploy to docker-hub for dev
          services:
            - docker
          script:
            - export IMAGE=hawkmanlabs/nsoroma-tracker-monitoring-service
            - export IMAGE_NAME=hawkmanlabs/nsoroma-tracker-monitoring-service:stable

            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAGE

    feature/dual-reports:
      - step: &build-deploy-docker-feature
          name: build and deploy to docker-hub for dev
          services:
            - docker
          script:
            - export IMAGE=hawkmanlabs/nsoroma-tracker-monitoring-service
            - export IMAGE_NAME=hawkmanlabs/nsoroma-tracker-monitoring-service:feature

            - docker build -t $IMAGE_NAME .
            - docker login --username $DOCKER_HUB_USERNAME --password $DOCKER_HUB_PASSWORD
            - docker push $IMAG

definitions:
  services:
    docker:
      memory: 3048  #increasing docker memory size
